"""Word document generation using python-docx."""

import io

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH


def generate_docx(content: dict, title: str) -> bytes:
    """Generate a Word document from structured content.

    Args:
        content: Dict with keys like 'sections', 'safety_warnings', 'specs', etc.
        title: Document title.

    Returns:
        DOCX file bytes.
    """
    doc = Document()

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle / metadata
    if content.get("subtitle"):
        sub = doc.add_paragraph(content["subtitle"])
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph("")  # spacer

    # Sections
    for section in content.get("sections", []):
        doc.add_heading(section.get("heading", ""), level=1)

        if section.get("safety_warning"):
            warning_para = doc.add_paragraph()
            run = warning_para.add_run(f"⚠ SAFETY WARNING: {section['safety_warning']}")
            run.bold = True
            run.font.color.rgb = None  # Would need RGBColor for red

        if section.get("body"):
            doc.add_paragraph(section["body"])

        if section.get("steps"):
            for i, step in enumerate(section["steps"], 1):
                doc.add_paragraph(f"{i}. {step}", style="List Number")

        if section.get("specs"):
            table = doc.add_table(rows=1, cols=3)
            table.style = "Table Grid"
            hdr = table.rows[0].cells
            hdr[0].text = "Parameter"
            hdr[1].text = "Value"
            hdr[2].text = "Source"

            for spec in section["specs"]:
                row = table.add_row().cells
                row[0].text = spec.get("parameter", "")
                row[1].text = spec.get("value", "")
                row[2].text = spec.get("source", "")

    # Footer disclaimer
    doc.add_paragraph("")
    disclaimer = doc.add_paragraph(
        "Generated by ManualWorx. Always verify critical specifications "
        "against the original service manual. Confidence scores indicate "
        "AI certainty and should not replace manufacturer documentation."
    )
    disclaimer.runs[0].font.size = Pt(8)
    disclaimer.runs[0].italic = True

    # Write to bytes
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()
